
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include \
					-I$(srctree)/drivers/misc/mediatek/include/mt-plat \
					-I$(srctree)/drivers/misc/mediatek/base/power/$(MTK_PLATFORM)

obj-$(CONFIG_NFC_PN547) += pn547.o
